[package]
name = "aprs"
version = "0.1.0"
authors = ["italic <italic.rendezvous@gmail.com>"]

[dependencies]
# log = "0.3.8"
lazy_static = "0.2.8"
# byteorder = "1.1.0"
# unicode-segmentation = "1.1.0"
